class State:
    stateToId = {
        "Distrito Federal": 330029,
        "Rio de Janeiro": 330041,
        "Ecatepec de Morelos": 974,
        "Estado de Mexico": 241,
        "Aragua": 329902,
        "Australian Capital Territory": 3358,
        "Wien": 3380,
        "Guangzhou": 329198,
        "Shanghai": 3667,
        "Anhui": 3642,
        "Beijing": 3643,
        "Chongqing": 3644,
        "Fujian": 3645,
        "Gansu": 3646,
        "Guangdong": 3647,
        "Guangxi": 3648,
        "Guizhou": 3649,
        "Hainan": 3650,
        "Hebei": 3651,
        "Heilongjiang": 3652,
        "Henan": 3653,
        "Hong Kong": 3654,
        "Hubei": 3655,
        "Hunan": 3656,
        "Inner Mongolia": 3657,
        "Jiangsu": 3658,
        "Jiangxi": 3659,
        "Jilin": 3660,
        "Liaoning": 3661,
        "Macau": 3662,
        "Ningxia": 3663,
        "Qinghai": 3664,
        "Shaanxi": 3665,
        "Shandong": 3666,
        "Shanghai": 3667,
        "Shanxi": 3668,
        "Sichuan": 3669,
        "Tianjin": 3670,
        "Tibet": 3671,
        "Xinjiang": 3672,
        "Yunnan": 3673,
        "Zhejiang": 3674,
        "Guangzhou": 329198
    }

    stateTo_cad_tipo_entidad = {
        "Distrito Federal": "Estado",
        "Rio de Janeiro": "Estado",
        "Ecatepec de Morelos": "Municipio",
        "Estado de Mexico": "Entidad Federativa",
        "Aragua": "Estado",
        "Australian Capital Territory": "Ciudad",
        "Wien": "Ciudad",
        "Guangzhou": "Entidad Federativa",
        "Shanghai": "Entidad Federativa",
        "Anhui": "Entidad Federativa",
        "Beijing": "Entidad Federativa",
        "Chongqing": "Entidad Federativa",
        "Fujian": "Entidad Federativa",
        "Gansu": "Entidad Federativa",
        "Guangdong": "Entidad Federativa",
        "Guangxi": "Entidad Federativa",
        "Guizhou": "Entidad Federativa",
        "Hainan": "Entidad Federativa",
        "Hebei": "Entidad Federativa",
        "Heilongjiang": "Entidad Federativa",
        "Henan": "Entidad Federativa",
        "Hong Kong": "Entidad Federativa",
        "Hubei": "Entidad Federativa",
        "Hunan": "Entidad Federativa",
        "Inner Mongolia": "Entidad Federativa",
        "Jiangsu": "Entidad Federativa",
        "Jiangxi": "Entidad Federativa",
        "Jilin": "Entidad Federativa",
        "Liaoning": "Entidad Federativa",
        "Macau": "Entidad Federativa",
        "Ningxia": "Entidad Federativa",
        "Qinghai": "Entidad Federativa",
        "Shaanxi": "Entidad Federativa",
        "Shandong": "Entidad Federativa",
        "Shanghai": "Entidad Federativa",
        "Shanxi": "Entidad Federativa",
        "Sichuan": "Entidad Federativa",
        "Tianjin": "Entidad Federativa",
        "Tibet": "Entidad Federativa",
        "Xinjiang": "Entidad Federativa",
        "Yunnan": "Entidad Federativa",
        "Zhejiang": "Entidad Federativa",
        "Guangzhou": "Entidad Federativa"
    }

    stateTo_id_tipo_entidad = {
        "Distrito Federal": 7,
        "Rio de Janeiro": 7,
        "Ecatepec de Morelos": 2,
        "Estado de Mexico": 1,
        "Aragua": 7,
        "Australian Capital Territory": 5,
        "Wien": 5,
        "Guangzhou": 1,
        "Shanghai": 1,
        "Anhui": 1,
        "Beijing": 1,
        "Chongqing": 1,
        "Fujian": 1,
        "Gansu": 1,
        "Guangdong": 1,
        "Guangxi": 1,
        "Guizhou": 1,
        "Hainan": 1,
        "Hebei": 1,
        "Heilongjiang": 1,
        "Henan": 1,
        "Hong Kong": 1,
        "Hubei": 1,
        "Hunan": 1,
        "Inner Mongolia": 1,
        "Jiangsu": 1,
        "Jiangxi": 1,
        "Jilin": 1,
        "Liaoning": 1,
        "Macau": 1,
        "Ningxia": 1,
        "Qinghai": 1,
        "Shaanxi": 1,
        "Shandong": 1,
        "Shanghai": 1,
        "Shanxi": 1,
        "Sichuan": 1,
        "Tianjin": 1,
        "Tibet": 1,
        "Xinjiang": 1,
        "Yunnan": 1,
        "Zhejiang": 1,
        "Guangzhou": 1
    }

    stateToCountryId = {
        "Distrito Federal": 30,
        "Rio de Janeiro": 30,
        "Ecatepec de Morelos": 142,
        "Estado de Mexico": 142,
        "Aragua": 237,
        "Australian Capital Territory": 13,
        "Wien": 14,
        "Guangzhou": 44,
        "Shanghai": 44,
        "Anhui": 44,
        "Beijing": 44,
        "Chongqing": 44,
        "Fujian": 44,
        "Gansu": 44,
        "Guangdong": 44,
        "Guangxi": 44,
        "Guizhou": 44,
        "Hainan": 44,
        "Hebei": 44,
        "Heilongjiang": 44,
        "Henan": 44,
        "Hong Kong": 44,
        "Hubei": 44,
        "Hunan": 44,
        "Inner Mongolia": 44,
        "Jiangsu": 44,
        "Jiangxi": 44,
        "Jilin": 44,
        "Liaoning": 44,
        "Macau": 44,
        "Ningxia": 44,
        "Qinghai": 44,
        "Shaanxi": 44,
        "Shandong": 44,
        "Shanghai": 44,
        "Shanxi": 44,
        "Sichuan": 44,
        "Tianjin": 44,
        "Tibet": 44,
        "Xinjiang": 44,
        "Yunnan": 44,
        "Zhejiang": 44,
        "Guangzhou": 44
    }

    def __init__(self, state=None):
        if state is None:
            self.state_id = 3380
            self.var_cad_tipo_entidad = "Ciudad"
            self.var_id_tipo_entidad = 5
            self.var_cad_entidad = "Wien"
            self.var_oficina = True
            self.var_id_pais = 14
            self.var_id_entidad = 3380
        else:
            self.state_id = self.stateToId.get(state)
            self.var_cad_tipo_entidad = self.stateTo_cad_tipo_entidad.get(state)
            self.var_id_tipo_entidad = self.stateTo_id_tipo_entidad.get(state)
            self.var_cad_entidad = state
            self.var_oficina = True
            self.var_id_pais = self.stateToCountryId.get(state)
            self.var_id_entidad = self.stateToId.get(state)